// <auto-generated />
using System;
using System.Diagnostics.CodeAnalysis;
using Management.System.Infrastructure.Management.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace Management.System.Infrastructure.Migrations;

[ExcludeFromCodeCoverage]
[DbContext(typeof(Context))]
partial class ContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.2")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Management.System.Domain.Entities.CustomerEntity", b =>
            {
                b.Property<Guid>("CustomerId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasDefaultValueSql("uuid_generate_v4()");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.HasKey("CustomerId");

                b.ToTable("Customers");
            });

        modelBuilder.Entity("Management.System.Domain.Entities.OrderEntity", b =>
            {
                b.Property<Guid>("OrderId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasDefaultValueSql("uuid_generate_v4()");

                b.Property<Guid>("CustomerId")
                    .HasColumnType("uuid");

                b.Property<string>("DeliveryAddress")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("NumberAddress")
                    .HasColumnType("integer");

                b.Property<DateTime>("OrderDate")
                    .HasColumnType("timestamp");

                b.Property<decimal>("Price")
                    .HasColumnType("numeric");

                b.Property<Guid>("ProductId")
                    .HasColumnType("uuid");

                b.Property<int>("Quantity")
                    .HasColumnType("integer");

                b.Property<int>("Status")
                    .HasColumnType("integer");

                b.Property<string>("ZipCode")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("OrderId");

                b.ToTable("Orders");
            });

        modelBuilder.Entity("Management.System.Domain.Entities.ProductEntity", b =>
            {
                b.Property<Guid>("ProductId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasDefaultValueSql("uuid_generate_v4()");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<decimal>("Price")
                    .HasColumnType("numeric");

                b.Property<int>("Quantity")
                    .HasColumnType("integer");

                b.HasKey("ProductId");

                b.ToTable("Products");
            });

        modelBuilder.Entity("Management.System.Domain.Entities.UserEntity", b =>
            {
                b.Property<Guid>("UserId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasDefaultValueSql("uuid_generate_v4()");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Password")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("UserName")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("UserType")
                    .HasColumnType("integer");

                b.HasKey("UserId");

                b.ToTable("Users");
            });
#pragma warning restore 612, 618
    }
}
